### ISSUE TITLE
关于docker run之后post参数

### ISSUE THREAD

**Issue by Cccc-ll** [YinAoXiong/12306_code_server#12]
作者，您好！
  我将您的docker  run之后 不知道具体怎么提交，能否将post提交的规范详细一些呢？ 我尝试了不同的提交均失败告终，无奈请教您！！盼相助

**Comment by cg-llc** [comment]
> 我尝试了不同的提交均失败告终，无奈请教您！！盼相助！作者，您好！我将您的docker run之后，不知道具体怎么提交，能否将post提交的规范详细一些呢？

**Comment by yinaoxiong** [comment]
> 作者，您好！
> 我将您的docker run之后 不知道具体怎么提交，能否将post提交的规范详细一些呢？ 我尝试了不同的提交均失败告终，无奈请教您！！盼相助

你会用postman吗？我导出了一份我测试用的一个collection，你可以下载查看一下参数，以及本地测试一下。
https://www.getpostman.com/collections/d402f985c78880040590

**Comment by Cccc-ll** [comment]
> > 我尝试了不同的提交均失败告终，无奈请教您！！盼相助！作者，您好！我将您的docker run之后，不知道具体怎么提交，能否将post提交的规范详细一些呢？
> 
> 你会用邮递员吗？我导出了一份我测试用的一个集合，你可以下载查看一下参数，以及本地测试一下。
> https://www.getpostman.com/collections/d402f985c78880040590

好的，谢谢您   我去研究一下

**Comment by Cccc-ll** [comment]
> > 作者，您好！
> > 我将您的docker run之后 不知道具体怎么提交，能否将post提交的规范详细一些呢？ 我尝试了不同的提交均失败告终，无奈请教您！！盼相助
> 
> 你会用postman吗？我导出了一份我测试用的一个collection，你可以下载查看一下参数，以及本地测试一下。
> https://www.getpostman.com/collections/d402f985c78880040590
十分感激您的帮助，已经测试成功了   谢谢您
