### ISSUE TITLE
请问这个怎么解决

### ISSUE THREAD

**Issue by Eco1i** [YinAoXiong/12306_code_server#14]
您已设置使用云打码，但是服务器资源有限，请尽快改为本地打码
验证码识别坐标为184,77,184,149
184,77,184,149
验证码通过,开始登录..
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302

**Comment by yinaoxiong** [comment]
> 

看起来像是抢票软件的问题的样子，感觉应该去那边提个issue，验证码已经验证通过了
