### ISSUE TITLE
如何测试是否运行成功?

### ISSUE THREAD

**Issue by 1036956372** [YinAoXiong/12306_code_server#2]
RT,已安装，后台运行gunicorn,不知道如何测试?

**Comment by yinaoxiong** [comment]
> RT,已安装，后台运行gunicorn,不知道如何测试?

@1036956372 gunicorn 默认运行在80端口。目前项目内还没有写测试内容（之后考虑加入），可以先使用postman 之类工具按照文档中的接口规范进行测试

**Comment by yinaoxiong** [comment]
@1036956372 之前源码部署部分忘记加上下载模型的部分，现在补上了

**Comment by 1036956372** [comment]
_ok，我也一点不懂python，服务器要是装不上12306就用分流抢票了
