### ISSUE TITLE
Inter处理器算什么平台

### ISSUE THREAD

**Issue by wwb306** [YinAoXiong/12306_code_server#5]
请问 Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz 处理器应该是intel平台么？不在这个amd和arm范围内吧？

**Comment by yinaoxiong** [comment]
> 请问 Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz 处理器应该是intel平台么？不在这个amd和arm范围内吧？

@wwb306  这里的amd64和arm64v8等是表示处理器架构的意思，amd64就等于x86-64也等于x64。
你直接用amd64的就可以了

**Comment by yinaoxiong** [comment]
@wwb306  用docker 的话现在已经支持manifest，你直接docker pull yinaoxiong/12306_code_server，就可以了，会自动选择对应的平台和系统
