### ISSUE TITLE
tflite支持macOS平台的路径是什么？

### ISSUE THREAD

**Issue by iT-Boyer** [YinAoXiong/12306_code_server#6]
2. 安装依赖 自行根据平台和python选择对应的tflite（下面的例子为amd64，python3.7）
`pip3 install -r requirements.txt`
```
ERROR: tflite_runtime-1.14.0-cp37-cp37m-linux_x86_64.whl is not a supported wheel on this platform.
```

**Comment by yinaoxiong** [comment]
> 1. 安装依赖 自行根据平台和python选择对应的tflite（下面的例子为amd64，python3.7）
>    `pip3 install -r requirements.txt`
> 
> ```
> ERROR: tflite_runtime-1.14.0-cp37-cp37m-linux_x86_64.whl is not a supported wheel on this platform.
> ```

@huos3203  你是不是在Windows上安装的啊？

**Comment by iT-Boyer** [comment]
是macOS 上安装的，提示上述错误了。

**Comment by yinaoxiong** [comment]
@huos3203 啊哦，看到了，你是在mac上部署的啊，谷歌官方提供的的tflite 没有mac版本的。
你可以考虑在电脑上安装tensorflow，然后将app.py的第8行从
```
import tflite_runtime.interpreter as tflite
```
改为
```
import tensorflow.lite as tflite
```
我在Windows上测试通过了，手头上没有mac

**Comment by iT-Boyer** [comment]
好的，我尝试下
