### ISSUE TITLE
gunicorn 命令报错

### ISSUE THREAD

**Issue by eyesmoons** [YinAoXiong/12306_code_server#9]
执行gunicorn app:app -c gunicorn.conf.py时报错：
-bash: gunicorn: command not found

**Comment by yinaoxiong** [comment]
@eyesmoons  你是在什么平台上运行的啊？运行之前有安装好依赖吗？有可能是依赖没有装好吧

**Comment by eyesmoons** [comment]
> @eyesmoons 你是在什么平台上运行的啊？运行之前有安装好依赖吗？有可能是依赖没有装好吧

Centos7上面。通过pip3 install gunicorn 安装的

**Comment by yinaoxiong** [comment]
如果依赖装好了，但还是出现这个问题的话，可能是你pip3 安装包的位置没有在path里面吧，所以就找不到，如果还是解决不了的话建议你直接用容器运行吧。

**Comment by eyesmoons** [comment]
好的，谢谢~
